# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [1]:
# Exercise 1
import numpy as np
array = np.arange(1, 11)
print(array)


[ 1  2  3  4  5  6  7  8  9 10]



---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [3]:
# Exercise 2
import numpy as np
zeros_array = np.zeros((3, 3), dtype=int)
print(zeros_array)


[[0 0 0]
 [0 0 0]
 [0 0 0]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [4]:
# Exercise 3
import numpy as np

evenly_spaced = np.linspace(0, 5, 10)
print(evenly_spaced)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]



---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [5]:
# Exercise 4
import numpy as np

identity_matrix = np.identity(5, dtype=int)
print(identity_matrix)


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]



---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [6]:
# Exercise 5
import numpy as np

random_matrix = np.random.rand(4, 4)
print(random_matrix)


[[0.02192545 0.67853457 0.22284696 0.54604753]
 [0.02471463 0.58813023 0.21111944 0.34372048]
 [0.06690899 0.19199056 0.02276793 0.21050036]
 [0.90557687 0.4069771  0.84218644 0.19281677]]



---

### Exercise 6:
Find the shape of a NumPy array.


In [7]:
# Exercise 6
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)


(2, 3)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [8]:
# Exercise 7
import numpy as np

array_1d = np.arange(16)  
array_2d = array_1d.reshape(4, 4)
print(array_2d)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [9]:
# Exercise 8
import numpy as np

array = np.array([1, 2, 3])
print(array.dtype)


int32



---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [11]:
# Exercise 9
import numpy as np
array = np.arange(1, 101)
even_numbers = array[array % 2 == 0]
print(even_numbers)


[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [12]:
# Exercise 10
import numpy as np

random_matrix = np.random.randint(10, 51, size=(6, 6))
print(random_matrix)


[[49 48 13 38 32 32]
 [15 39 30 23 43 42]
 [35 39 13 19 34 47]
 [36 39 17 49 16 34]
 [44 27 16 29 24 14]
 [24 22 44 10 27 29]]



---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [13]:
# Exercise 11
import numpy as np

matrix = np.array([
    [1,  2,  3,  4,  5],
    [6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

submatrix = matrix[0:3, 0:3]
print(submatrix)


[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]



---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [14]:
# Exercise 12
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
total_sum = array.sum()
print(total_sum)


21



---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [15]:
# Exercise 13
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])

mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [16]:
# Exercise 14
import numpy as np

array = np.array([4, 7, 1, 9, 3, 6])

maximum = np.max(array)
minimum = np.min(array)

print("Maximum value:", maximum)
print("Minimum value:", minimum)


Maximum value: 9
Minimum value: 1



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [17]:
# Exercise 15
import numpy as np
array = np.random.randint(1, 101, size=20)
max_index = np.argmax(array)
print("Array:", array)
print("Maximum value:", array[max_index])
print("Index of maximum value:", max_index)


Array: [  1  62  84   5   4  40  17  25  81  39  77  28  91 100  95  71 100  96
  77   5]
Maximum value: 100
Index of maximum value: 13



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [18]:
# Exercise 16
import numpy as np

array = np.array([1, 2, 3, 4, 5])
reversed_array = array[::-1]

print("Original:", array)
print("Reversed:", reversed_array)


Original: [1 2 3 4 5]
Reversed: [5 4 3 2 1]



---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [19]:
# Exercise 17
import numpy as np

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

result = matrix1 * matrix2

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Element-wise multiplication:\n", result)


Matrix 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Element-wise multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [20]:
# Exercise 18
import numpy as np

array = np.array([10, 20, 30, 40])

diagonal_matrix = np.diag(array)

print("1D Array:", array)
print("Diagonal Matrix:\n", diagonal_matrix)


1D Array: [10 20 30 40]
Diagonal Matrix:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]



---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [21]:
# Exercise 19
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])


result = A @ B

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix multiplication result:\n", result)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix multiplication result:
 [[19 22]
 [43 50]]



---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [22]:
# Exercise 20
import numpy as np

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])
flat_array = array_2d.flatten()
print("Original 2D array:\n", array_2d)
print("Flattened 1D array:", flat_array)


Original 2D array:
 [[1 2 3]
 [4 5 6]]
Flattened 1D array: [1 2 3 4 5 6]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [23]:
# Exercise 21
import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])
vertical_stack = np.vstack((array1, array2))
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Vertically stacked arrays:\n", vertical_stack)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Vertically stacked arrays:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [24]:
# Exercise 22
import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

horizontal_stack = np.hstack((array1, array2))
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Horizontally stacked arrays:\n", horizontal_stack)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Horizontally stacked arrays:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]



---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [25]:
# Exercise 23
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])

sub_arrays = np.split(array, 3)

for i, sub in enumerate(sub_arrays):
    print(f"Sub-array {i}:", sub)


Sub-array 0: [1 2]
Sub-array 1: [3 4]
Sub-array 2: [5 6]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [26]:
# Exercise 24
import numpy as np

random_array = np.random.rand(3, 3)

rounded_array = np.round(random_array, 2)

print("Random array:\n", random_array)
print("\nRounded array:\n", rounded_array)


Random array:
 [[0.88802495 0.66752964 0.01340281]
 [0.05303461 0.95385059 0.20406685]
 [0.30126413 0.31466834 0.41805267]]

Rounded array:
 [[0.89 0.67 0.01]
 [0.05 0.95 0.2 ]
 [0.3  0.31 0.42]]



---

### Exercise 25:
Find the unique elements of a NumPy array.


In [27]:
# Exercise 25
import numpy as np

array = np.array([1, 2, 2, 3, 4, 4, 5, 1, 6])

unique_elements = np.unique(array)

print("Original array:", array)
print("Unique elements:", unique_elements)


Original array: [1 2 2 3 4 4 5 1 6]
Unique elements: [1 2 3 4 5 6]



---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [28]:
# Exercise 26
import numpy as np

array = np.array([1, 5, 3, 7, 2, 8, 4])
threshold = 4
array[array < threshold] = threshold

print(array)


[4 5 4 7 4 8 4]



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [29]:
# Exercise 27
import numpy as np

array = np.array([1, 2, 3, 4, 5])

cumulative_sum = np.cumsum(array)

print("Original array:", array)
print("Cumulative sum:", cumulative_sum)


Original array: [1 2 3 4 5]
Cumulative sum: [ 1  3  6 10 15]



---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [30]:
# Exercise 28
import numpy as np

array = np.array([0, 1, 2, 0, 3, 0, 4])

non_zero_count = np.count_nonzero(array)

print("Array:", array)
print("Number of non-zero elements:", non_zero_count)


Array: [0 1 2 0 3 0 4]
Number of non-zero elements: 4



---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [31]:
# Exercise 29
import numpy as np
random_array = np.random.randint(0, 100, size=10)

sorted_array = np.sort(random_array)

print("Random array:", random_array)
print("Sorted array:", sorted_array)


Random array: [38 66 95  7 38 12 90 20 21  2]
Sorted array: [ 2  7 12 20 21 38 38 66 90 95]



---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [32]:
# Exercise 30
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_sum = matrix.sum(axis=1)
column_sum = matrix.sum(axis=0)

print("Matrix:\n", matrix)
print("Row-wise sum:", row_sum)
print("Column-wise sum:", column_sum)


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [33]:
# Exercise 31
import numpy as np
array = np.random.rand(3, 3) * 100  # random values between 0 and 100
normalized_array = (array - array.min()) / (array.max() - array.min())

print("Original array:\n", array)
print("\nNormalized array:\n", normalized_array)


Original array:
 [[61.90497918  9.68507829 73.96925908]
 [35.07947679 62.72545111 97.02443907]
 [58.45630351 42.86654412  2.05587666]]

Normalized array:
 [[0.6301991  0.08033397 0.75723356]
 [0.34773192 0.63883851 1.        ]
 [0.59388523 0.42972818 0.        ]]



---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [34]:
# Exercise 32
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

dot_product = np.dot(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Dot product:", dot_product)


Array 1: [1 2 3]
Array 2: [4 5 6]
Dot product: 32



---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [35]:
# Exercise 33
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

trace_value = np.trace(matrix)

print("Matrix:\n", matrix)
print("Trace of the matrix:", trace_value)


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace of the matrix: 15



---

### Exercise 34:
Create a 2D array and swap two rows.


In [36]:
# Exercise 34
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Original array:\n", array)

array[[0, 2]] = array[[2, 0]]

print("\nArray after swapping rows 0 and 2:\n", array)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after swapping rows 0 and 2:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]



---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [37]:
# Exercise 35
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5])
column_vector = array_1d.reshape(-1, 1)

print("1D array:", array_1d)
print("Column vector:\n", column_vector)


1D array: [1 2 3 4 5]
Column vector:
 [[1]
 [2]
 [3]
 [4]
 [5]]



---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [38]:
# Exercise 36
import numpy as np

matrix = np.array([[1, 2, 3],
                   [0, 1, 4],
                   [5, 6, 0]])

determinant = np.linalg.det(matrix)

print("Matrix:\n", matrix)
print("Determinant:", determinant)


Matrix:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
Determinant: 0.9999999999999987



---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [39]:
# Exercise 37
import numpy as np

matrix = np.array([[4, 2],
                   [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Matrix:\n", matrix)
print("\nEigenvalues:", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)


Matrix:
 [[4 2]
 [1 3]]

Eigenvalues: [5. 2.]

Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [40]:
# Exercise 38
import numpy as np

# Coefficient matrix A
A = np.array([[2, 3],
              [5, 1]])

# Right-hand side vector b
b = np.array([8, 7])

# Solve for x
x = np.linalg.solve(A, b)

print("Solution:", x)


Solution: [1. 2.]



---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [41]:
# Exercise 39
import numpy as np

array = np.array([10, 20, 30, 40, 50])

mean = 0
std_dev = 5

noise = np.random.normal(mean, std_dev, size=array.shape)

noisy_array = array + noise

print("Original array:", array)
print("Noise:", noise)
print("Noisy array:", noisy_array)


Original array: [10 20 30 40 50]
Noise: [ 3.15250738e-01  5.26908956e-01 -2.16223128e+00 -4.75054814e-03
  1.01504905e+01]
Noisy array: [10.31525074 20.52690896 27.83776872 39.99524945 60.15049051]



---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [42]:
# Exercise 40
import numpy as np
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

diagonal_elements = np.diagonal(matrix)

print("Matrix:\n", matrix)
print("Diagonal elements:", diagonal_elements)


Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagonal elements: [ 1  6 11 16]



---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [43]:
# Exercise 41
import numpy as np
random_values = np.random.uniform(0, 100, 100)
clipped_values = np.clip(random_values, 10, 50)

print("Original values:\n", random_values)
print("\nClipped values:\n", clipped_values)


Original values:
 [17.71226282  3.03750886 23.81896962 16.40270301 20.28555165 22.05510423
 75.13887736 13.60418358 99.41778733 45.02064451 26.41429737 63.92649098
 94.44626965 45.86340633 29.34157564 57.85354247 89.49281414 71.2536339
 65.50573336 51.71035896  7.59819208 33.91562218 40.4895449  62.12922985
 38.39576804 77.54593097 93.70258699 92.42061483 48.40330274 56.21337191
 82.92747163 87.36611001 90.91334676 74.48827471 65.90999675 89.39686726
 84.00237803 36.99060026  0.98754522  6.34571652 48.27349327 35.06678455
 64.51619687 24.3229298  31.65893525 45.38215868 60.72948682 30.84352836
 13.52845789  7.98949862 31.47576604 52.48247759 55.14481893 52.84998793
 36.9334941  89.05154202 64.66568648 55.74866658 42.69060932 88.2204605
 94.06708413 79.87538985 34.59600016 68.91375803  4.57542505 88.12187927
 62.81244134 10.32983346 73.07332571 52.81080287 12.07449962 58.4777075
 80.10620316 31.91621221 67.24692423 74.97228158 93.50749959 82.49001341
 18.39478046 28.23663165 24.2593003 


---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [44]:
# Exercise 42
import numpy as np

array = np.array([[ 1, -2,  3],
                  [-4,  5, -6],
                  [ 7, -8,  9]])

print("Original array:\n", array)

array[array < 0] = 0

print("\nArray after replacing negatives with zero:\n", array)


Original array:
 [[ 1 -2  3]
 [-4  5 -6]
 [ 7 -8  9]]

Array after replacing negatives with zero:
 [[1 0 3]
 [0 5 0]
 [7 0 9]]



---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [45]:
# Exercise 43
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

inner_product = np.inner(a, b)

outer_product = np.outer(a, b)

print("Array a:", a)
print("Array b:", b)
print("\nInner product:", inner_product)
print("\nOuter product:\n", outer_product)


Array a: [1 2 3]
Array b: [4 5 6]

Inner product: 32

Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [46]:
# Exercise 44
import numpy as np
from scipy.spatial import distance

points = np.array([[1, 2],
                   [4, 6],
                   [7, 8],
                   [2, 1]])

dist_matrix = distance.cdist(points, points, metric='euclidean')

print("Points:\n", points)
print("\nPairwise distance matrix:\n", dist_matrix)


Points:
 [[1 2]
 [4 6]
 [7 8]
 [2 1]]

Pairwise distance matrix:
 [[0.         5.         8.48528137 1.41421356]
 [5.         0.         3.60555128 5.38516481]
 [8.48528137 3.60555128 0.         8.60232527]
 [1.41421356 5.38516481 8.60232527 0.        ]]



---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [47]:
# Exercise 45
import numpy as np

dtype = [('name', 'U10'), ('age', 'i4'), ('height', 'f4')]

# Create an array with sample data
data = np.array([
    ('Alice', 25, 5.5),
    ('Bob', 30, 6.0),
    ('Charlie', 22, 5.8)
], dtype=dtype)

print(data)
print("\nNames:", data['name'])
print("Ages:", data['age'])
print("Heights:", data['height'])


[('Alice', 25, 5.5) ('Bob', 30, 6. ) ('Charlie', 22, 5.8)]

Names: ['Alice' 'Bob' 'Charlie']
Ages: [25 30 22]
Heights: [5.5 6.  5.8]



---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [48]:
# Exercise 46
import numpy as np

matrix = np.random.randint(0, 10, size=(5, 5))

print("Matrix:\n", matrix)

unique_values, counts = np.unique(matrix, return_counts=True)

print("\nUnique values:", unique_values)
print("Counts:", counts)


Matrix:
 [[5 7 3 1 6]
 [9 8 3 2 5]
 [6 6 7 1 5]
 [7 8 3 0 8]
 [8 7 3 1 7]]

Unique values: [0 1 2 3 5 6 7 8 9]
Counts: [1 3 1 4 3 3 5 4 1]



---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [49]:
# Exercise 47
import numpy as np

arr = np.random.rand(3, 3)

print("Original array:\n", arr)


row_means = arr.mean(axis=1, keepdims=True)

centered_arr = arr - row_means

print("\nRow means:\n", row_means)
print("\nArray after subtracting row means:\n", centered_arr)


Original array:
 [[0.65073081 0.31938287 0.45082287]
 [0.97783005 0.04126617 0.82199489]
 [0.69089911 0.68154859 0.03064583]]

Row means:
 [[0.47364552]
 [0.61369704]
 [0.46769784]]

Array after subtracting row means:
 [[ 0.1770853  -0.15426265 -0.02282265]
 [ 0.36413301 -0.57243087  0.20829785]
 [ 0.22320127  0.21385074 -0.43705201]]



---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [50]:
# Exercise 48
import numpy as np

arr = np.random.randint(0, 101, size=20)

print("Array:", arr)

any_greater_than_50 = np.any(arr > 50)

print("Any value greater than 50?", any_greater_than_50)


Array: [  7  27  16  62  12   5  86  40  33  78  77  85  32  47  90  82  27 100
  26  93]
Any value greater than 50? True



---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [51]:
# Exercise 49
import numpy as np

def moving_average(arr, k):
    window = np.ones(k) / k
    return np.convolve(arr, window, mode='valid')


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Window size
k = 3

ma = moving_average(arr, k)
print("Original array:", arr)
print(f"Moving average with window size {k}:", ma)


Original array: [1 2 3 4 5 6 7 8 9]
Moving average with window size 3: [2. 3. 4. 5. 6. 7. 8.]



---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [52]:
# Exercise 50
import numpy as np

# Sample arrays
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])

corr_matrix = np.corrcoef(x, y)


pearson_corr = corr_matrix[0, 1]

print("Pearson correlation coefficient:", pearson_corr)


Pearson correlation coefficient: -0.9999999999999999



---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [53]:
# Exercise 51
import numpy as np

radians = np.array([0, np.pi/6, np.pi/4, np.pi/2, np.pi])

degrees = np.degrees(radians)

print("Radians:", radians)
print("Degrees:", degrees)


Radians: [0.         0.52359878 0.78539816 1.57079633 3.14159265]
Degrees: [  0.  30.  45.  90. 180.]



---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [54]:
# Exercise 52
import numpy as np

arr = np.random.rand(10)

print("Array:", arr)

variance = np.var(arr)

std_dev = np.std(arr)

print("Variance:", variance)
print("Standard Deviation:", std_dev)


Array: [0.02311029 0.54792282 0.01864843 0.6309947  0.32751184 0.6646513
 0.75941561 0.67491567 0.89211388 0.9975751 ]
Variance: 0.10058459536253476
Standard Deviation: 0.3171507454863298



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [55]:
# Exercise 53
import numpy as np
arr = np.array([[3, 7, 2, 5],
                [8, 1, 9, 4],
                [6, 3, 5, 7]])

print("Array:\n", arr)

max_indices_rows = np.argmax(arr, axis=1)

max_indices_cols = np.argmax(arr, axis=0)

print("\nIndices of max values along each row:", max_indices_rows)
print("Indices of max values along each column:", max_indices_cols)


Array:
 [[3 7 2 5]
 [8 1 9 4]
 [6 3 5 7]]

Indices of max values along each row: [1 2 3]
Indices of max values along each column: [1 0 1 2]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [56]:
# Exercise 54
import numpy as np

matrix = np.array([[4, 7],
                   [2, 6]])

print("Original matrix:\n", matrix)

inverse_matrix = np.linalg.inv(matrix)

print("\nInverse matrix:\n", inverse_matrix)


Original matrix:
 [[4 7]
 [2 6]]

Inverse matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]



---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [57]:
# Exercise 55
import numpy as np

arr = np.random.rand(10)

print("Original array:", arr)

standardized_arr = (arr - np.mean(arr)) / np.std(arr)

print("Standardized array:", standardized_arr)
print("Mean of standardized array:", np.mean(standardized_arr))
print("Standard deviation of standardized array:", np.std(standardized_arr))


Original array: [0.66132204 0.4861577  0.93249997 0.40189217 0.73130805 0.02849798
 0.86889069 0.735351   0.00144644 0.63396   ]
Standardized array: [ 0.37046252 -0.20284031  1.25801225 -0.47863653  0.59952268 -1.70073419
  1.04982274  0.61275504 -1.78927232  0.28090812]
Mean of standardized array: 4.829470157119431e-16
Standard deviation of standardized array: 1.0



---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [58]:
# Exercise 56
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
addition = arr1 + arr2
subtraction = arr1 - arr2

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Addition:", addition)
print("Subtraction:", subtraction)


Array 1: [1 2 3 4 5]
Array 2: [5 4 3 2 1]
Addition: [6 6 6 6 6]
Subtraction: [-4 -2  0  2  4]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [59]:
# Exercise 57
import numpy as np
arr = np.random.rand(10)

print("Array:", arr)

max_index = np.argmax(arr)

print("Index of maximum element:", max_index)
print("Maximum element:", arr[max_index])


Array: [0.22912013 0.39908162 0.14470426 0.35624486 0.33372569 0.92311957
 0.86702883 0.15467762 0.74533601 0.52714519]
Index of maximum element: 5
Maximum element: 0.9231195677895111



---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [60]:
# Exercise 58
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original array:\n", arr)

rotated_arr = np.rot90(arr)

print("\nRotated array by 90 degrees:\n", rotated_arr)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Rotated array by 90 degrees:
 [[3 6 9]
 [2 5 8]
 [1 4 7]]



---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [61]:
# Exercise 59
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

frobenius_norm = np.linalg.norm(matrix)

print("Matrix:\n", matrix)
print("Frobenius norm:", frobenius_norm)


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Frobenius norm: 16.881943016134134



---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [62]:
# Exercise 60
import numpy as np
arr = np.arange(3*4*5).reshape(3, 4, 5)

print("Original 3D array:\n", arr)
subarray = arr[0:2, 1:4, 2:5]

print("\nSliced subarray:\n", subarray)


Original 3D array:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]

Sliced subarray:
 [[[ 7  8  9]
  [12 13 14]
  [17 18 19]]

 [[27 28 29]
  [32 33 34]
  [37 38 39]]]



---